server:
  error:
    include-stacktrace: on-param
spring:
  profiles:
    active:
    - dev
  jpa:
    open-in-view: false
# spring:
#   jpa:
#     database: postgresql
#     show-sql: true
#     hibernate:
#       ddl-auto: update
#   datasource:
#     url: jdbc:postgresql://localhost:5432/btspring
#     username: btspring
#     password: btspring